import "./globals.css";
import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";

const spacegrotesk = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bloombot - Learning. Reimagined.",
  description: "Generated by create next app",
  authors: [{ name: "Plastic Labs", url: "https://plasticlabs.ai" }],
  openGraph: {
    title: "Bloombot",
    description: "Bloom is your always-on, always-engaged learning companion. You can chat with Bloom about any topic, whenever you want. It’s designed to help you build critical skills and follow your curiosity.",
    siteName: "Bloombot",
    type: "website",
    url: "https://bloombot.ai",
    locale: "en_US",
  }
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={spacegrotesk.className}>{children}</body>
    </html>
  );
}
